package e_bebek.test.tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
//Generated by Selenium IDE
import org.openqa.selenium.devtools.v107.runtime.model.Timestamp;
import org.openqa.selenium.By;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;
	import org.openqa.selenium.remote.DesiredCapabilities;
	import org.openqa.selenium.Dimension;
	import org.openqa.selenium.WebElement;
	import org.openqa.selenium.interactions.Actions;
	import org.openqa.selenium.support.ui.ExpectedConditions;
	import org.openqa.selenium.support.ui.WebDriverWait;
	import org.openqa.selenium.JavascriptExecutor;
	import org.openqa.selenium.Alert;
	import org.openqa.selenium.Keys;
	import java.util.*;
	import java.net.MalformedURLException;
	import java.net.URL;

public class Test1 {

	
	public static void main(String[] args) throws InterruptedException {
		
		Map<String, Object> vars;
		  
	
		System.setProperty("chromeDriver","drivers/chromedriver");
		WebDriver driver = new ChromeDriver();
	
		JavascriptExecutor executor = (JavascriptExecutor)driver;
		
		
		driver.get("https://e-bebek.com/");//go website
		driver.manage().window().setSize(new Dimension(1051, 846));
	    Thread.sleep(2000); //waiting main page
	    WebElement searchBox = driver.findElement(By.id("txtSearchBox"));//click searchbox
	    driver.findElement(By.cssSelector(".search-wrapper")).click();
	    driver.findElement(By.id("txtSearchBox")).sendKeys("biberon");//write biberon and seach
	    driver.findElement(By.id("txtSearchBox")).sendKeys(Keys.ENTER);
	    executor.executeScript("window.scrollTo(0,244)");
	    driver.findElement(By.id("addToCartBtn")).click();//I cant find the right cartButton
	    driver.findElement(By.id("btnShowCart")).click();

	   
	    WebElement element = driver.findElement(By.cssSelector(".col-6:nth-child(3) .product-item-anchor .product-item-content"));
	    Actions builder = new Actions(driver);
	    builder.moveToElement(element).perform();
	
		driver.quit();

	}

}
